export const countryList = [
  "Afghanistan",
  "Åland Islands",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros",
  "Congo",
  "Congo, The Democratic Republic of Congo",
  "Cook Islands",
  "Costa Rica",
  "Cote D'ivoire",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands (Malvinas)",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-bissau",
  "Guyana",
  "Haiti",
  "Heard Island and Mcdonald Islands",
  "Holy See (Vatican City State)",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, Democratic People's Republic of Korea",
  "Korea, Republic of Korea",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libyan Arab Jamahiriya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mayotte",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "Netherlands Antilles",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestinian Territory, Occupied",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Reunion",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Saint Helena",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Pierre and Miquelon",
  "Saint Vincent and The Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and The South Sandwich Islands",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "United States Minor Outlying Islands",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Viet Nam",
  "Virgin Islands, British",
  "Virgin Islands, U.S.",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const stateList = [
  "Abuja FCT",
  "Abia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "Cross River",
  "Delta",
  "Ebonyi",
  "Edo",
  "Ekiti",
  "Enugu",
  "Gombe",
  "Imo",
  "Jigawa",
  "Kaduna",
  "Kano",
  "Katsina",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Nassarawa",
  "Niger",
  "Ogun",
  "Ondo",
  "Osun",
  "Oyo",
  "Plateau",
  "Sokoto",
  "Taraba",
  "Yobe",
  "Zamfara",
];

export const itemsData = [
  {
    _id: "52Ghdt36d4374",
    img: "/images/cloth1.png",
    item_name: "The Adire Attire",
    category: "Adire",
    original_price: 150000,
    new_price: 100000,
    item_slug: "adire-attire-150000",
    description:
      "Embrace the vibrant beauty of African culture with our stunning African print design gown. This eye-catching piece features a bold, colorful pattern that celebrates traditional artistry while offering a modern silhouette.",
    images: [
      "/images/cloth1.png",
      "/images/cloth1.png",
      "/images/cloth1.png",
      "/images/cloth1.png",
    ],
    sizes: [
      {
        size: "S",
        original_price: 150000,
        new_price: 100000,
      },
      {
        size: "M",
        original_price: 150000,
        new_price: 100000,
      },
      {
        size: "L",
        original_price: 150000,
        new_price: 100000,
      },
      {
        size: "XL",
        original_price: 150000,
        new_price: 120000,
      },
      {
        size: "2XL",
        original_price: 150000,
        new_price: 120000,
      },
    ],
    colors: ["red", "blue", "yellow", "green", "white", "black"],
  },
  {
    _id: "52dghedt36d4374",
    img: "/images/cloth1.png",
    item_name: "Female Suit",
    category: "Suit",
    original_price: 145000,
    new_price: 125000,
    item_slug: "adire-attire-145000",
    description:
      "Embrace the vibrant beauty of African culture with our stunning African print design gown. This eye-catching piece features a bold, colorful pattern that celebrates traditional artistry while offering a modern silhouette.",
    images: ["/images/cloth1.png", "/images/cloth1.png", "/images/cloth1.png"],
    colors: ["red", "blue", "yellow", "green", "white", "black"],
  },
  {
    _id: "98jhJKDKfrt36d4374",
    img: "/images/cloth1.png",
    item_name: "The Adire Attire",
    category: "Adire",
    original_price: 80000,
    new_price: 70000,
    item_slug: "adire-attire-75000",
    description:
      "Embrace the vibrant beauty of African culture with our stunning African print design gown. This eye-catching piece features a bold, colorful pattern that celebrates traditional artistry while offering a modern silhouette.",
    images: ["/images/cloth1.png", "/images/cloth1.png", "/images/cloth1.png"],
    sizes: [
      {
        size: "S",
        original_price: 150000,
        new_price: 120000,
      },
      {
        size: "M",
        original_price: 150000,
        new_price: 120000,
      },
      {
        size: "L",
        original_price: 150000,
        new_price: 120000,
      },
      {
        size: "XL",
        original_price: 150000,
        new_price: 120000,
      },
      {
        size: "2XL",
        original_price: 150000,
        new_price: 120000,
      },
    ],
    colors: ["red", "blue", "yellow", "green", "white", "black"],
  },
  {
    _id: "29jkDHgenddrr437oir",
    img: "/images/cloth1.png",
    item_name: "Male Suit",
    category: "Suit",
    original_price: 200000,
    new_price: 180000,
    item_slug: "adire-attire-180000",
    description:
      "Embrace the vibrant beauty of African culture with our stunning African print design gown. This eye-catching piece features a bold, colorful pattern that celebrates traditional artistry while offering a modern silhouette.",
    images: ["/images/cloth1.png", "/images/cloth1.png", "/images/cloth1.png"],
    sizes: [
      {
        size: "S",
        original_price: 200000,
        new_price: 180000,
      },
      {
        size: "M",
        original_price: 200000,
        new_price: 180000,
      },
      {
        size: "L",
        original_price: 200000,
        new_price: 180000,
      },
      {
        size: "XL",
        original_price: 200000,
        new_price: 185000,
      },
      {
        size: "2XL",
        original_price: 200000,
        new_price: 185000,
      },
    ],
    colors: ["red", "blue", "yellow", "green", "white", "black"],
  },
  {
    _id: "lkfjoGhdt36ddg63",
    img: "/images/cloth1.png",
    item_name: "Italian Top",
    category: "Top",
    original_price: 45000,
    new_price: 45000,
    item_slug: "adire-attire-45000",
    description:
      "Embrace the vibrant beauty of African culture with our stunning African print design gown. This eye-catching piece features a bold, colorful pattern that celebrates traditional artistry while offering a modern silhouette.",
    images: ["/images/cloth1.png", "/images/cloth1.png", "/images/cloth1.png"],
    sizes: [
      {
        size: "S",
        original_price: 45000,
        new_price: 45000,
      },
      {
        size: "M",
        original_price: 45000,
        new_price: 45000,
      },
      {
        size: "L",
        original_price: 45000,
        new_price: 45000,
      },
      {
        size: "XL",
        original_price: 45000,
        new_price: 45000,
      },
      {
        size: "2XL",
        original_price: 45000,
        new_price: 45000,
      },
    ],
    colors: ["red", "blue", "yellow", "green", "white", "black"],
  },
  {
    _id: "llk393852Ghdt36d4374",
    img: "/images/cloth1.png",
    item_name: "Female Bag",
    category: "Bag",
    original_price: 65500,
    new_price: 65500,
    item_slug: "adire-attire-65500",
    description:
      "Embrace the vibrant beauty of African culture with our stunning African print design gown. This eye-catching piece features a bold, colorful pattern that celebrates traditional artistry while offering a modern silhouette.",
    images: ["/images/cloth1.png", "/images/cloth1.png", "/images/cloth1.png"],
    sizes: [
      {
        size: "S",
        original_price: 65500,
        new_price: 65500,
      },
      {
        size: "M",
        original_price: 65500,
        new_price: 65500,
      },
      {
        size: "L",
        original_price: 65500,
        new_price: 65500,
      },
      {
        size: "XL",
        original_price: 65500,
        new_price: 65500,
      },
      {
        size: "2XL",
        original_price: 65500,
        new_price: 65500,
      },
    ],
    colors: ["red", "blue", "yellow", "green", "white", "black"],
  },
  {
    _id: "kflijje3dt36d4374",
    img: "/images/cloth1.png",
    item_name: "Adire Jacket",
    category: "Adire",
    original_price: 120000,
    new_price: 100000,
    item_slug: "adire-attire-100000",
    description:
      "Embrace the vibrant beauty of African culture with our stunning African print design gown. This eye-catching piece features a bold, colorful pattern that celebrates traditional artistry while offering a modern silhouette.",
    images: ["/images/cloth1.png", "/images/cloth1.png", "/images/cloth1.png"],
    sizes: [
      {
        size: "S",
        original_price: 120000,
        new_price: 100000,
      },
      {
        size: "M",
        original_price: 120000,
        new_price: 100000,
      },
      {
        size: "L",
        original_price: 120000,
        new_price: 100000,
      },
      {
        size: "XL",
        original_price: 120000,
        new_price: 100000,
      },
      {
        size: "2XL",
        original_price: 120000,
        new_price: 100000,
      },
    ],
    colors: ["red", "blue", "yellow", "green", "white", "black"],
  },
  {
    _id: "bnhgg336d4374",
    img: "/images/cloth1.png",
    item_name: "Adire Bagging",
    category: "Adire",
    original_price: 28550,
    new_price: 28550,
    item_slug: "adire-attire-28550",
    description:
      "Embrace the vibrant beauty of African culture with our stunning African print design gown. This eye-catching piece features a bold, colorful pattern that celebrates traditional artistry while offering a modern silhouette.",
    images: ["/images/cloth1.png", "/images/cloth1.png", "/images/cloth1.png"],
    sizes: [
      {
        size: "S",
        original_price: 28550,
        new_price: 28550,
      },
      {
        size: "M",
        original_price: 28550,
        new_price: 28550,
      },
      {
        size: "L",
        original_price: 28550,
        new_price: 28550,
      },
      {
        size: "XL",
        original_price: 28550,
        new_price: 28550,
      },
      {
        size: "2XL",
        original_price: 28550,
        new_price: 28550,
      },
    ],
    colors: ["red", "blue", "yellow", "green", "white", "black"],
  },
];

export const reviewsData = [
  {
    owner: "52Ghdt36d4374",
    reviewer: "Tee King",
    rating: 4,
    review: "Very great product",
  },
  {
    owner: "52Ghdt36d4374",
    reviewer: "Debby",
    rating: 3,
    review: "Very great product",
  },
  {
    owner: "52dghedt36d4374",
    reviewer: "Moses",
    rating: 3,
    review: "Very great product",
  },
  {
    owner: "98jhJKDKfrt36d4374",
    reviewer: "Moses",
    rating: 5,
    review: "Very great product",
  },
  {
    owner: "98jhJKDKfrt36d4374",
    reviewer: "Tee King",
    rating: 2,
    review: "Not good enough",
  },
  {
    owner: "52dghedt36d4374",
    reviewer: "Moses",
    rating: 5,
    review: "Very great product",
  },
  {
    owner: "bnhgg336d4374",
    reviewer: "Debby",
    rating: 4,
    review: "Very good product",
  },
  {
    owner: "52Ghdt36d4374",
    reviewer: "Tee King",
    rating: 5,
    review: "Very great product",
  },
  {
    owner: "bnhgg336d4374",
    reviewer: "Mariam",
    rating: 3,
    review: "Not too bad for such product",
  },
  {
    owner: "52Ghdt36d4374",
    reviewer: "Moses",
    rating: 5,
    review: "Very great product",
  },
  {
    owner: "52dghedt36d4374",
    reviewer: "Tee King",
    rating: 5,
    review: "Very great product",
  },
  {
    owner: "52dghedt36d4374",
    reviewer: "Moses",
    rating: 4,
    review: "Managable product till I can get a better one",
  },
  {
    owner: "bnhgg336d4374",
    reviewer: "Tee King",
    rating: 5,
    review: "Very great product",
  },
  {
    owner: "52dghedt36d4374",
    reviewer: "Debby",
    rating: 5,
    review: "Very great product",
  },
  {
    owner: "52dghedt36d4374",
    reviewer: "Mariam",
    rating: 2,
    review: "Very bad product",
  },
  {
    owner: "98jhJKDKfrt36d4374",
    reviewer: "Mariam",
    rating: 5,
    review: "Very great product",
  },
  {
    owner: "52Ghdt36d4374",
    reviewer: "Kazeem",
    rating: 4,
    review: "Very great product",
  },
  {
    owner: "52dghedt36d4374",
    reviewer: "Mariam",
    rating: 5,
    review: "Very great product",
  },
  {
    owner: "llk393852Ghdt36d4374",
    reviewer: "Debby",
    rating: 5,
    review: "Very great product",
  },
  {
    owner: "llk393852Ghdt36d4374",
    reviewer: "Tee King",
    rating: 5,
    review: "Very great product",
  },
  {
    owner: "52Ghdt36d4374",
    reviewer: "Kazeem",
    rating: 4,
    review: "Very great product",
  },
  {
    owner: "52Ghdt36d4374",
    reviewer: "Tee King",
    rating: 2,
    review: "One of the worst product here",
  },
  {
    owner: "llk393852Ghdt36d4374",
    reviewer: "Debby",
    rating: 5,
    review: "Very great product",
  },
];

export const exploreMoreData = [
  {
    img: "/images/explore-11.png",
    title: "Set",
    link: "set",
  },
  {
    img: "/images/explore-22.png",
    title: "Dress",
    link: "dress",
  },
  {
    img: "/images/explore-33.png",
    title: "Playsuit",
    link: "playsuit",
  },
  {
    img: "/images/explore-44.png",
    title: "Short",
    link: "short",
  },
];

export const discountData = {
  percent: 5,
};

export const shippingData = [
  {
    location: "Within Lagos, (1 day)",
    amount: 500,
  },
  {
    location: "Within Lagos, (1 day)",
    amount: 2000,
  },
  {
    location: "Within Lagos, (1 day)",
    amount: 25000,
  },
];

export const ordersData = [
  {
    _id: "35dhrtrtGYe736y",
    img: "/images/cloth1.png",
    order_title: "Adire Attire XL Blue",
    order_qty: 5,
    items_total: 150000,
    shipping: 1500,
    total_paid: 151500,
    created_at: "2024-11-16T17:13:01.561+00:00",
  },
  {
    _id: "35dhrtrtGYe736y",
    img: "/images/cloth1.png",
    order_title: "Ladies Suit LG Green",
    order_qty: 3,
    items_total: 85000,
    shipping: 1500,
    total_paid: 86500,
    created_at: "2024-11-16T17:13:01.561+00:00",
  },
  {
    _id: "35dhrtrtGYe736y",
    img: "/images/cloth1.png",
    order_title: "Ladies Suit XL Red",
    order_qty: 8,
    items_total: 150000,
    shipping: 1500,
    total_paid: 151500,
    created_at: "2024-11-16T17:13:01.561+00:00",
  },
  {
    _id: "35dhrtrtGYe736y",
    img: "/images/cloth1.png",
    order_title: "Ladies Suit XL Red",
    order_qty: 8,
    items_total: 150000,
    shipping: 1500,
    total_paid: 151500,
    created_at: "2024-11-16T17:13:01.561+00:00",
  },
  {
    _id: "35dhrtrtGYe736y",
    img: "/images/cloth1.png",
    order_title: "Ladies Suit XL Red",
    order_qty: 8,
    items_total: 150000,
    shipping: 1500,
    total_paid: 151500,
    created_at: "2024-11-16T17:13:01.561+00:00",
  },
  {
    _id: "35dhrtrtGYe736y",
    img: "/images/cloth1.png",
    order_title: "Ladies Suit XL Red",
    order_qty: 8,
    items_total: 150000,
    shipping: 1500,
    total_paid: 151500,
    created_at: "2024-11-16T17:13:01.561+00:00",
  },
  {
    _id: "35dhrtrtGYe736y",
    img: "/images/cloth1.png",
    order_title: "Ladies Suit XL Red",
    order_qty: 8,
    items_total: 150000,
    shipping: 1500,
    total_paid: 151500,
    created_at: "2024-11-16T17:13:01.561+00:00",
  },
  {
    _id: "35dhrtrtGYe736y",
    img: "/images/cloth1.png",
    order_title: "Ladies Suit XL Red",
    order_qty: 8,
    items_total: 150000,
    shipping: 1500,
    total_paid: 151500,
    created_at: "2024-11-16T17:13:01.561+00:00",
  },
  {
    _id: "35dhrtrtGYe736y",
    img: "/images/cloth1.png",
    order_title: "Ladies Suit XL Red",
    order_qty: 8,
    items_total: 150000,
    shipping: 1500,
    total_paid: 151500,
    created_at: "2024-11-16T17:13:01.561+00:00",
  },
  {
    _id: "35dhrtrtGYe736y",
    img: "/images/cloth1.png",
    order_title: "Ladies Suit XL Red",
    order_qty: 8,
    items_total: 150000,
    shipping: 1500,
    total_paid: 151500,
    created_at: "2024-11-16T17:13:01.561+00:00",
  },
];
